--- Logging error ---
Traceback (most recent call last):
  File "/home/matthewz03/.conda/envs/pytorch/lib/python3.11/logging/__init__.py", line 1114, in emit
    self.flush()
  File "/home/matthewz03/.conda/envs/pytorch/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/home/matthewz03/.conda/envs/pytorch/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/home/matthewz03/.conda/envs/pytorch/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/matthewz03/.conda/envs/pytorch/lib/python3.11/site-packages/ipykernel/parentpoller.py", line 38, in run
    get_logger().warning("Parent appears to have exited, shutting down.")
Message: 'Parent appears to have exited, shutting down.'
